const PLATFORM_TYPE = {
  ANDROID: 1,
  IOS: 2,
  MAC: 3,
  FIRE_OS: 4,
  GEAR_VR: 5,
  HOLOLENS: 6,
  WINDOWS_10: 7,
  WINDOWS_32_BIT: 8,
  DEDICATED: 9,
  TV_OS: 10,
  PLAYSTATION_4: 11,
  NINTENDO_SWITCH: 12,
  XBOX_ONE: 13,
  WINDOWS_PHONE: 14,
  LINUX: 15
};

const RARITY = {
  COMMON: 0,
  UNCOMMON: 1,
  RARE: 2,
  EPIC: 3,
  LEGENDARY: 4
};

module.exports = { PLATFORM_TYPE, RARITY };